#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 06 20:52:33 CEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_tlc_behav -key {Behavioral:sim_1:Functional:tb_tlc} -tclbatch tb_tlc.tcl -view /home/anonym/Desktop/DE1_PC/Digital-electronics-1/Labs/08-traffic_lights/traffic/tb_tlc_behav.wcfg -log simulate.log"
xsim tb_tlc_behav -key {Behavioral:sim_1:Functional:tb_tlc} -tclbatch tb_tlc.tcl -view /home/anonym/Desktop/DE1_PC/Digital-electronics-1/Labs/08-traffic_lights/traffic/tb_tlc_behav.wcfg -log simulate.log

