#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun May 02 00:18:18 CEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_displayer_behav -key {Behavioral:sim_1:Functional:tb_displayer} -tclbatch tb_displayer.tcl -view /home/anonym/Desktop/project_1/tb_displayer_behav.wcfg -log simulate.log"
xsim tb_displayer_behav -key {Behavioral:sim_1:Functional:tb_displayer} -tclbatch tb_displayer.tcl -view /home/anonym/Desktop/project_1/tb_displayer_behav.wcfg -log simulate.log

